image: node:lts-alpine # Image chosen

stages: # List of stages for jobs, and their order of execution
    - build
    - test

.yarn-install:
    before_script:
        - yarn

build-job: # This job runs in the build stage, which runs first.
    extends: .yarn-install
    stage: build
    only:
        - main
    script:
        - echo "Dependencies installed!"
        - yarn run generate
        - echo "Everything works!"

lint-test-job: # This job also runs in the test stage.
    extends: .yarn-install
    stage: test    # It can run at the same time as unit-test-job (in parallel).
    only: # Only run this on Merge Request
        - "merge_request"
    script:
        - yarn run lint

e2e-test-job: # This job runs in the test stage.
    extends: .yarn-install
    image: cypress/browsers:node18.12.0-chrome107
    stage: test    # It only starts when the job in the build stage completes successfully.
    only: # Only run this on Merge Request
        - "merge_request"
    script:
        - chmod +x .gitlab/e2e.sh
        - ./.gitlab/e2e.sh
